=== bridobony/angular-libraries/projects/test-angular-controls/src/assets/config/navbar.schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "logo": {
      "type": "string"
    },
    "logotext": {
      "type": "string"
    },
    "left": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/Left"
      }
    },
    "right": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/Right"
      }
    }
  },
  "definitions": {
    "Submenu": {
      "type": "object",
      "properties": {
        "label": {
          "type": "string"
        },
        "url": {
          "type": "string"
        }
      }
    },
    "Left": {
      "type": "object",
      "properties": {
        "label": {
          "type": "string"
        },
        "url": {
          "type": "string"
        },
        "icon": {
          "type": "string"
        },
        "submenu": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/Submenu"
          }
        }
      }
    },
    "Right": {
      "type": "object",
      "properties": {
        "label": {
          "type": "string"
        },
        "url": {
          "type": "string"
        },
        "icon": {
          "type": "string"
        }
      }
    }
  }
}

=== bridobony/angular-libraries/projects/test-angular-controls/src/assets/config/sample.json
{
  "logo": "images/logo.png",
  "logotext": "My Site",
  "left": [
    {
      "label": "First Menu",
      "url": "route",
      "icon": "fas fa-concierge-bell",
      "submenu": [
        {
          "label": "label",
          "url": "url"
        }
      ]
    },
    {
      "label": "Button",
      "url": "route",
      "icon": "fas fa-info-circle"
    }

  ],
  "right": [
    {
      "label": "Right Button",
      "url": "route",
      "icon": "fas fa-info-circle"
    }
  ]
}

=== bridobony/angular-libraries/projects/test-angular-controls/src/assets/config/navbar.json
{
  "logo": "images/logo_sm.png",
  "logotext": "Nav<br/> Bar",
  "left": [
    {
      "label": "Home",
      "url": "/",
      "icon": "fas fa-home"
    },
    {
      "label": "About",
      "url": "/about",
      "icon": "fas fa-info-circle"
    },
    {
      "label": "Services",
      "icon": "fas fa-concierge-bell",
      "submenu": [
        {
          "label": "Consulting",
          "url": "/services/consulting"
        },
        {
          "label": "Development",
          "url": "/services/development"
        }
      ]
    },
    {
      "label": "Contact",
      "url": "/contact",
      "icon": "fas fa-envelope"
    }
  ],
  "right": [
    {
      "label": "Profile",
      "url": "/profile",
      "icon": "fas fa-user"
    },
    {
      "label": "Settings",
      "url": "/settings",
      "icon": "fas fa-cog"
    },
    {
      "url": "/logout",
      "icon": "fas fa-sign-out-alt"
    }
  ]
}

=== bridobony/angular-libraries/config/sitenav.json
{
  "logo": "images/logo.png",
  "logotext": "",
  "left": [
    {
      "label": "Home",
      "url": "/",
      "icon": "fas fa-home"
    },
    {
      "label": "Navigation",
      "icon": "fas fa-concierge-bell",
      "submenu": [
        {
          "label": "Site Nav",
          "url": "/sitenav",
          "icon": "fas fa-info-circle"
        },
        {
          "label": "Card Nav Panel",
          "url": "/cardnavpanel"
        }
      ]
    }
  ],
  "right": [
    {
      "label": "Profile",
      "url": "/profile",
      "icon": "fas fa-user"
    },
    {
      "url": "/settings",
      "icon": "fas fa-cog"
    },
    {
      "url": "/logout",
      "icon": "fas fa-sign-out-alt"
    }
  ]
}
